spring:
  application:
    name: service-auth
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.169.0.103:3306/mybatis-security?useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: '088114'
  redis:
    host: 192.169.0.103
    port: 6379
    password: avicit
    database: 0
mybatis:
  mapper-locations: classpath:mapper/*.xml
