spring:
  application:
    name: service-auth
  profiles:
    active: dev
  redis:
    host: 192.168.0.103
    port: 6379
    password: "dy088114"
    database: 0
mybatis:
  mapper-locations: classpath:mapper/*.xml
